"""Pydantic request/response schemas for the orchestrator service."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import UTC, datetime
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field


class Attachment(BaseModel):
    """Attachment metadata supplied with an inbound message."""

    type: str = Field(..., description="Attachment type hint (image, file, etc).")
    url: AnyUrl | None = Field(default=None, description="Optional CDN URL for the attachment.")
    metadata: Mapping[str, Any] | None = Field(
        default=None, description="Free-form attachment metadata."
    )


class InboundMessageRequest(BaseModel):
    """Normalized inbound message payload."""

    id: UUID
    tenant_id: UUID
    brand_id: UUID
    channel_id: UUID
    conversation_id: UUID
    sender_id: str = Field(..., min_length=1, max_length=120)
    content: str = Field(..., min_length=1, description="User-provided message body.")
    received_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))
    locale: str | None = Field(default=None, max_length=16)
    attachments: Sequence[Attachment] = Field(default_factory=list)
    metadata: Mapping[str, Any] | None = Field(default=None)


class ContextSnippet(BaseModel):
    """Snippet returned from the retrieval pipeline."""

    id: str
    text: str
    score: float | None = None
    metadata: Mapping[str, Any] | None = None


class OutboundMessagePayload(BaseModel):
    """Outbound response generated by the orchestrator."""

    message_id: UUID
    content: str
    persona_prompt: str | None = Field(
        default=None, description="Persona prompt applied to craft the response."
    )
    trace_id: str
    context: Sequence[ContextSnippet] = Field(default_factory=list)


class InboundMessageResponse(BaseModel):
    """Envelope returned after processing an inbound message."""

    conversation_id: UUID
    outbound: OutboundMessagePayload


class KnowledgeUploadResponse(BaseModel):
    """Metadata returned after staging a knowledge document for ingestion."""

    knowledge_source_id: UUID
    filename: str
    status: str


class ConversationMessage(BaseModel):
    """Historic conversation message representation."""

    id: UUID
    direction: str
    role: str
    content: str
    created_at: datetime
    metadata: Mapping[str, Any] | None = None


class ConversationHistoryResponse(BaseModel):
    """Conversation history payload."""

    conversation_id: UUID
    channel_id: UUID | None
    status: str
    messages: Sequence[ConversationMessage]
