"""HTTP response schemas and helpers shared by FastAPI services."""

from __future__ import annotations

from collections.abc import Mapping
from http import HTTPStatus
from typing import Any, Generic, TypeVar

from pydantic import AnyUrl, BaseModel, Field

from .errors import CoreError


class ProblemDetail(BaseModel):
    """RFC 9457 compatible error payload."""

    type: AnyUrl | None = Field(
        default=None, description="URI reference that identifies the problem type."
    )
    title: str = Field(
        ..., description="Short, human-readable summary of the problem type."
    )
    status: int = Field(
        ..., description="HTTP status code generated by the origin server."
    )
    detail: str | None = Field(
        default=None,
        description="Human-readable explanation specific to this occurrence of the problem.",
    )
    instance: AnyUrl | None = Field(
        default=None,
        description="URI reference that identifies the specific occurrence of the problem.",
    )
    code: str | None = Field(default=None, description="Machine readable error code.")
    extras: Mapping[str, Any] | None = Field(
        default=None,
        description="Additional metadata to help clients act on the problem.",
    )

    @classmethod
    def from_core_error(cls, exc: CoreError) -> ProblemDetail:
        """Create a problem detail payload from a ``CoreError`` instance."""

        payload = exc.to_dict()
        extras = payload.pop("details", None)
        return cls(
            type=payload.get("type"),
            title=payload["title"],
            status=payload["status"],
            code=payload.get("code"),
            detail=payload.get("detail"),
            extras=extras,
        )


class HealthResponse(BaseModel):
    """Simple health check payload."""

    status: str = Field(default="ok")
    version: str | None = None


T = TypeVar("T")


class ResponseEnvelope(BaseModel, Generic[T]):
    """Standard envelope for successful responses."""

    data: T
    meta: Mapping[str, Any] | None = None
    trace_id: str | None = None


def to_problem_response(exc: Exception) -> ProblemDetail:
    """Convert an exception into a ``ProblemDetail`` record."""

    if isinstance(exc, CoreError):
        return ProblemDetail.from_core_error(exc)

    return ProblemDetail(
        type=None,
        title=str(exc),
        status=HTTPStatus.INTERNAL_SERVER_ERROR,
        detail=None,
        code="internal_server_error",
    )
